apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: headless-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: headless-nginx
    spec:
#      hostNetwork: true
      containers:
      - name: nginx
        image: harbor.product.co-mall/library/nginx:1.9
#        image: nginx:1.9
        ports:
        - containerPort: 80
          hostPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: headless-nginx
spec:
#  type: NodePort
#  sessionAffinity: ClientIP
  selector:
    app: headless-nginx
  ports:
  - port: 80
#    nodePort: 30081
  clusterIP: None

