apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: locust-ingress
  namespace: default
spec:
  rules:
  - host: locust.pf.co-mall
    http:
      paths:
      - path: /
        backend:
          serviceName: locust-master
          servicePort: 8089

