apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  selector:
    name: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whoami
  labels:
     name: whoami
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        name: whoami
    spec:
      containers:
      - name: whoami
        image: harbor.product.co-mall/platform/whoami
#        image: zhusl/whoami
        ports:
        - containerPort: 80

