apiVersion: v1
kind: Service
metadata:
  name: nginx-pvc-test
  labels:
    app: nginx-pvc-test
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-pvc-test
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-pvc-test
spec:
  serviceName: "nginx-pvc-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-pvc-test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
