apiVersion: v1
kind: Service
metadata:
  name: stateful-nginx
  labels:
    app: stateful-nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: stateful-nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: stateful-web
spec:
  serviceName: "stateful-nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: stateful-nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
#        volumeMounts:
#        - name: www
#          mountPath: /usr/share/nginx/html
#  volumeClaimTemplates:
#  - metadata:
#      name: www
#      annotations:
#        volume.beta.kubernetes.io/storage-class: anything
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 1Gi
