apiVersion: v1
kind: Service
metadata:
  name: zk3
  namespace: comall
spec:
  selector:
    app: zk3
  clusterIP: None
  ports:
    - name: foo # Actually, no port is needed.
      port: 2181
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk3
  namespace: comall
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk3
    spec:
      hostname: zk3
      subdomain: zk3
      containers:
      - image: harbor.product.co-mall/library/zookeeper:3.4.9
#      - image: zhusl/zookeeper:3.4.9
        env:
        - name: ZOO_MY_ID
          value: "3"
        - name: ZOO_SERVERS
          value: "server.1=zk1.zk1.comall.svc.cluster.local:2888:3888 server.2=zk2.zk2.comall.svc.cluster.local:2888:3888 server.3=0.0.0.0:2888:3888"
        name: zk
