kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
