kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-monitor-grafana-data
   namespace: monitoring
spec:
   accessModes:
#     - ReadWriteOnce
     - ReadWriteMany
   resources:
     requests:
       storage: 20Gi
   selector:
     matchLabels:
       pv: pv-monitor-grafana-data
