apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-test
  labels:
    pv: pv-gitlab-test
spec:
  capacity:
    storage: 22Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs/git-data-test2
    server: 10.90.26.9
