apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-comall-m2
  labels:
    pv: pv-jenkins-comall-m2
spec:
  capacity:
    storage: 20Gi
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs/01
    server: 10.90.26.9
