apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-comall-data
  labels:
    pv: pv-jenkins-comall-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs/02
    server: 10.90.26.9
