kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-jenkins-comall-m2
   namespace: comall
spec:
   accessModes:
#     - ReadWriteOnce
     - ReadWriteMany
   resources:
     requests:
       storage: 20Gi
   selector:
     matchLabels:
       pv: pv-jenkins-comall-m2
