apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
#  type: NodePort
  selector:
    name: frontend
  ports:
  - port: 80
#    nodePort: 30001

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
     name: frontend
spec:
     replicas: 2
     template: 
       metadata:
         labels:
           name: frontend
       spec:
         containers:
         - name: frontend
           image: kubeguide/guestbook-php-frontend
           ports:
           - containerPort: 80
           env:
           - name: GET_HOSTS_FROM
             value: env

