apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
#  type: NodePort
  selector:
    name: redis-master
  ports:
  - name: master-port
    port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
     name: redis-master
spec:
     replicas: 1
     selector:
       name: redis-master
     template: 
       metadata:
         labels:
           name: redis-master
       spec:
         containers:
         - name: master
           image: kubeguide/redis-master
           ports:
           - containerPort: 6379
