apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
#  type: NodePort
  selector:
    name: redis-slave
  ports:
  - name: slave-port
    port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
     name: redis-slave
spec:
     replicas: 2
     selector:
       name: redis-slave
     template: 
       metadata:
         labels:
           name: redis-slave
       spec:
         containers:
         - name: slave
           image: kubeguide/guestbook-redis-slave
           ports:
           - containerPort: 6379
           env:
           - name: GET_HOSTS_FROM
             value: env

