apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    log_bin_trust_function_creators=1
    lower_case_table_names=1
    character-set-server = utf8mb4
    open_files_limit = 65535
    max_connections = 500
    max_connect_errors = 1000000
    table_open_cache = 512
    max_allowed_packet = 128M
    sort_buffer_size = 4M
    join_buffer_size = 4M
    lock_wait_timeout = 3600 
    thread_cache_size = 512
    wait_timeout = 600
    tmp_table_size = 32M
    long_query_time = 1
    innodb_buffer_pool_size = 1024M
    innodb_open_files = 65535
  slave.cnf: |    
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    log_bin_trust_function_creators=1
    character-set-server = utf8mb4
    open_files_limit = 65535
    max_connections = 500
    max_connect_errors = 1000000
    table_open_cache = 512
    max_allowed_packet = 128M
    sort_buffer_size = 4M
    join_buffer_size = 4M
    lock_wait_timeout = 3600
    thread_cache_size = 512
    wait_timeout = 600
    tmp_table_size = 32M
    long_query_time = 1
    innodb_buffer_pool_size = 1024M
    innodb_open_files = 65535

