apiVersion: v1
data:
  prometheus.yaml: |+
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s

    # scrape_configs:
    remote_read:
      - url: 'http://prometheus:9090/api/v1/read'
        remote_timeout: 8s


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-core-readonly
  namespace: monitoring
