apiVersion: v1
data:
  cpu-usage.yml: |
    groups:
    - name: cpu.rule
      rules:
      - alert: NodeCPUUsage
        expr: (100 - (avg(irate(node_cpu{mode="idle",name="node-exporter"}[5m])) BY (instance)
          * 100)) > 75
        for: 2m
        labels:
          severity: Warning
        annotations:
          DESCRIPTION: '{{$labels.instance}}: CPU usage is above 75% (current value is:
            {{ $value }})'
          SUMMARY: '{{$labels.instance}}: High CPU usage detected'
  instance-availability.yml: |
    groups:
    - name: instance.rule
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: Critical
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
            for more than 1 minute.'
          summary: Instance {{ $labels.instance }} down
  low-disk-space.yml: |
    groups:
    - name: low-disk.rule
      rules:
      - alert: NodeLowRootDisk
        expr: ((node_filesystem_size{mountpoint="/root-disk"} - node_filesystem_free{mountpoint="/root-disk"})
          / node_filesystem_size{mountpoint="/root-disk"} * 100) > 75
        for: 2m
        labels:
          severity: Warning
        annotations:
          DESCRIPTION: '{{$labels.instance}}: Root disk usage is above 75% (current value
            is: {{ $value }})'
          SUMMARY: '{{$labels.instance}}: Low root disk space'
      - alert: NodeLowDataDisk
        expr: ((node_filesystem_size{mountpoint="/data-disk"} - node_filesystem_free{mountpoint="/data-disk"})
          / node_filesystem_size{mountpoint="/data-disk"} * 100) > 75
        for: 2m
        labels:
          severity: Warning
        annotations:
          DESCRIPTION: '{{$labels.instance}}: Data disk usage is above 75% (current value
            is: {{ $value }})'
          SUMMARY: '{{$labels.instance}}: Low data disk space'
  mem.usage.yml: |
    groups:
    - name: mem.rule
      rules:
      - alert: NodeSwapUsage
        expr: (((node_memory_SwapTotal - node_memory_SwapFree) / node_memory_SwapTotal)
          * 100) > 75
        for: 2m
        labels:
          severity: Warning
        annotations:
          DESCRIPTION: '{{$labels.instance}}: Swap usage usage is above 75% (current value
            is: {{ $value }})'
          SUMMARY: '{{$labels.instance}}: Swap usage detected'
      - alert: NodeMemoryUsage
        expr: (((node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) / (node_memory_MemTotal)
          * 100)) > 75
        for: 2m
        labels:
          severity: Warning
        annotations:
          DESCRIPTION: '{{$labels.instance}}: Memory usage is above 75% (current value
            is: {{ $value }})'
          SUMMARY: '{{$labels.instance}}: High memory usage detected'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: monitoring
