apiVersion: v1
kind: Service
metadata:
  name: prometheus-readonly
  namespace: monitoring
  labels:
    app: prometheus-readonly
    component: core-readonly
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      name: webui2
  selector:
    app: prometheus-readonly
    component: core-readonly
