apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: comall-admin-binding-dashboard
  namespace: comall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: comall
  namespace: comall

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comall
  namespace: comall
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

