apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  type: NodePort
  ports:
  - name: redis-slave
    port: 6379
    nodePort: 30080
  selector:
    app: redis-slave
