apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  serviceName: redis-slave
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis-slave
          image: registry.cn-hangzhou.aliyuncs.com/szss/redis:4.0.6
          imagePullPolicy: Always
          env:
            - name: PASSWORD
              value: "123456"
          ports:
            - containerPort: 6379
              name: redis-slave
          readinessProbe:
            exec:
              command: ['redis-cli','-a','123456', 'info', 'server']
          volumeMounts:
            - name: redis-slave-storage
              mountPath: /data
      volumes:
        - name: redis-slave-storage
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-slave
                topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: redis-slave-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
