apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    name: cybershop4-qa-web
    namespace: cybershop4-qa

spec:
    replicas: 
    template:
        metadata:
            labels:
                app: cybershop4-qa-web
        spec:
#            nodeSelector:
#                zone: K8S_NODE_ZONE
            containers:
            - name: cybershop4-qa-web
              image: harbor.product.co-mall/project_cybershop4-qa/cybershop4-qa-web
              imagePullPolicy: Always
              securityContext:
                privileged: true
#                seLinuxOptions:
#                  user: system_u
#                  role: object_r
#                  type: fusefs_t
#                  level: "s0:c123,c456"
              ports:
              - containerPort: 8080
              env:
#              - name:  "ENV_NAME"
#                value: "APP_ENV"
#              - name:  "ENV_ID"
#                value: "ENVIRONMENT_ID"
#              - name:  "APPNAME"
#                value: "APP_NAME"
#              - name:  "CONFIG_DIR"
#                value: "APP_CONFIG_DIR"
#              - name:  "CONTEXT_FILE"
#                value: "APP_CONTEXT_FILE"
#              - name:  "JAVA_OPTS"
#                value: "-XmsJAVA_MIN_MEM -XmxJAVA_MAX_MEM"
#              - name:  "LOG_REDIS_SERVER"
#                value: "LOG_REDIS_SERVER_V"
              resources:
                limits:
                  cpu: 
                  memory: 
                requests:
                  cpu: 
                  memory: 
#              livenessProbe:
#                exec:
#                  command:
#                  - sh
#                  - -c
#                  - "/health_check.sh LIVENESS_URL 8080"
#                initialDelaySeconds: LIVENESS_IDS
#                timeoutSeconds: LIVENESS_TIMEOUT
#                periodSeconds: LIVENESS_PERIOD
#              readinessProbe:
#                exec:
#                  command:
#                  - sh
#                  - -c
#                  - "/health_check.sh LIVENESS_URL 8080"
#                initialDelaySeconds: READINESS_IDS
#                timeoutSeconds: READINESS_TIMEOUT
#                periodSeconds: READINESS_PERIOD
